//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public long ID_Answer { get; set; }
        public long ID_Questuion { get; set; }
        public string Answer { get; set; }
        public string Accuracy { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
